---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: nginx-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment

  minReplicas: 2
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: nginx-pv

spec:
  capacity:
    storage: 1Gi

  accessModes:
  - ReadWriteOnce

  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nginx-pvc

spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
---
---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: nginx-stateful

spec:
  serviceName: nginx-service

  replicas: 2

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: nginx-daemon

spec:
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: batch/v1
kind: Job

metadata:
  name: job-demo

spec:
  template:
    spec:
      containers:
      - name: job
        image: busybox
        command: ["echo","Hello Job"]

      restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob

metadata:
  name: cron-demo

spec:
  schedule: "*/5 * * * *"

  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: busybox
            command: ["echo","Hello CronJob"]

          restartPolicy: Never
---


kubectl apply -f hpa.yml
kubectl apply -f pv.yml
kubectl apply -f pvc.yml
kubectl apply -f daemonset.yml
kubectl apply -f statefulset.yml
kubectl apply -f job.yml
kubectl apply -f cronjob.yml
kubectl get hpa
kubectl get pv
kubectl get pvc
kubectl get daemonset
kubectl get statefulset
kubectl get jobs
kubectl get cronjobs
kubectl delete hpa nginx-hpa
kubectl delete pv nginx-pv
kubectl delete pvc nginx-pvc
kubectl delete daemonset nginx-daemon
kubectl delete statefulset nginx-stateful
kubectl delete job job-demo
kubectl delete cronjob cron-demo