apiVersion: v1
kind: Namespace

metadata:
  name: dev
  labels:
    app: nginx-app

---
apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-configmap
  namespace: dev
  labels:
    app: nginx-app

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Nginx on Kubernetes</title>
    </head>
    <body>
      <h1>Hello from Nginx in Kubernetes 🚀</h1>
      <p>Namespace: dev</p>
      <p>Served using ConfigMap + Deployment + Service + Ingress</p>
    </body>
    </html>
---
apiVersion: v1
kind: Secret

metadat:
  name: nginx-secret
  namespace: dev
  labels:
    app: nginx-app
type: Opaque

data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: nginx-pvc
  namespace: dev
  labels:
    app: nginx-app

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: dev
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80 
      
        env:
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: username

        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password
  

        volumeMounts:
        - name: nginx-config-volume
          mountPath: /usr/share/nginx/html/index.html    
          subPath: index.html 
        - name: nginx-storage 
          mountPath: /usr/share/nginx/html/uploads 

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-configmap

      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc

---
apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  namespace: dev
  labels:
    app: nginx-app

spec:
  type: ClusterIP
  selector:
    app: nginx-app

  ports:
  - port: 80
    targetPort: 80      

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: nginx-ingress
  namespace: dev
  labels:
    app: nginx-app

spec:
  rules:
  - host: myapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: nginx-hpa
  namespace: dev

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment

  minReplicas: 2
  maxReplicas: 5

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

