apiVersion: v1
kind: Secret

metadata:
  name: db-secret

type: Opaque

data:
  username: YWRtaW4=
  password: cGFzc3dvcmQxMjM=



# kubectl apply -f secret.yml
# kubectl get secrets
# kubectl describe secret db-secret
# kubectl get secret db-secret -o yaml
#Inside container
# echo $DB_USER
# echo $DB_PASS
#================================
apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod

spec:
  containers:
  - name: nginx
    image: nginx

    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username

    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password


#====================================